app = "bus-track"
primary_region = "iad"  # US East (Virginia)

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "10000"
  PYTHON_VERSION = "3.9"

[[services]]
  internal_port = 10000
  protocol = "tcp"
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

  [[services.ports]]
    port = 80
    handlers = ["http"]
  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 500 