services:
  - type: web
    name: bus-track
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python server/socket_server.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: RENDER
        value: "true"
      - key: SSL_CERT_PATH
        sync: false  # This will be set in Render.com dashboard
      - key: SSL_KEY_PATH
        sync: false  # This will be set in Render.com dashboard
    plan: free 