services:
  - type: web
    name: bus-track
    env: python
    buildCommand: |
      pip install -r requirements.txt
      mkdir -p frontend
      cp frontend/* frontend/
    startCommand: python server/socket_server.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: RENDER
        value: "true"
    plan: free 