services:
  - type: web
    name: bus-tracker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python server/socket_server.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
    plan: free 