services:
  - type: web
    name: bus-track
    env: python
    buildCommand: |
      pip install -r requirements.txt
      echo "Current directory:"
      pwd
      echo "Directory contents before copy:"
      ls -la
      echo "Frontend directory contents:"
      ls -la frontend/
      echo "Copying frontend files..."
      cp -v frontend/index.html /opt/render/project/src/
      echo "Directory contents after copy:"
      ls -la
    startCommand: |
      echo "Starting server..."
      echo "Current directory contents:"
      ls -la
      python server/socket_server.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: RENDER
        value: "true"
    plan: free 